server:
  name: "My Modded Server"
  minecraft_version: "26.1.1"
  loader: "fabric" # vanilla | fabric | forge | neoforge | paper | purpur
  loader_version: "0.18.4"
  java_memory:
    min: "1G"
    max: "3G"
  motd: "A server built with Minecraft Server Deployer"
  level_seed: ""
  difficulty: "normal"
  gamemode: "survival"
  pvp: true
  online_mode: true
  allow_flight: false
  max_players: 10
  view_distance: 10
  simulation_distance: 10
  enable_command_block: false
  white_list: false
  spawn_protection: 0
  server_port: 25565
  eula: true

mod_sources:
  mode: "modrinth" # modrinth | local_only
  local_mods_dir: "local_mods"

packaging:
  output_dir: "output"
  include_docker: true
  include_start_scripts: true
